package hn.com.tigo.josm.orchestrator.adapter.cbs2.task;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2022-03-07T11:48:51.476-06:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "CBSQueryCustomerInfoTaskService",
                  wsdlLocation = "file:/C:/Users/htc/AppData/Local/Temp/tempdir5316969325034208095.tmp/CBSQueryCustomerInfoTaskService_1.wsdl",
                  targetNamespace = "http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/")
public class CBSQueryCustomerInfoTaskService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/", "CBSQueryCustomerInfoTaskService");
    public final static QName CBSQueryCustomerInfoTaskPort = new QName("http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/", "CBSQueryCustomerInfoTaskPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/htc/AppData/Local/Temp/tempdir5316969325034208095.tmp/CBSQueryCustomerInfoTaskService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CBSQueryCustomerInfoTaskService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/htc/AppData/Local/Temp/tempdir5316969325034208095.tmp/CBSQueryCustomerInfoTaskService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CBSQueryCustomerInfoTaskService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CBSQueryCustomerInfoTaskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CBSQueryCustomerInfoTaskService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CBSQueryCustomerInfoTaskService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CBSQueryCustomerInfoTaskService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CBSQueryCustomerInfoTaskService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CBSQueryCustomerInfoTask
     */
    @WebEndpoint(name = "CBSQueryCustomerInfoTaskPort")
    public CBSQueryCustomerInfoTask getCBSQueryCustomerInfoTaskPort() {
        return super.getPort(CBSQueryCustomerInfoTaskPort, CBSQueryCustomerInfoTask.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CBSQueryCustomerInfoTask
     */
    @WebEndpoint(name = "CBSQueryCustomerInfoTaskPort")
    public CBSQueryCustomerInfoTask getCBSQueryCustomerInfoTaskPort(WebServiceFeature... features) {
        return super.getPort(CBSQueryCustomerInfoTaskPort, CBSQueryCustomerInfoTask.class, features);
    }

}
