
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package hn.com.tigo.josm.orchestrator.adapter.cbs2.task;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2022-03-07T11:48:51.310-06:00
 * Generated source version: 3.3.7
 *
 */

@javax.jws.WebService(
                      serviceName = "CBSQueryCustomerInfoTaskService",
                      portName = "CBSQueryCustomerInfoTaskPort",
                      targetNamespace = "http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/",
                      wsdlLocation = "file:/C:/Users/htc/AppData/Local/Temp/tempdir5316969325034208095.tmp/CBSQueryCustomerInfoTaskService_1.wsdl",
                      endpointInterface = "hn.com.tigo.josm.orchestrator.adapter.cbs2.task.CBSQueryCustomerInfoTask")

public class CBSQueryCustomerInfoTaskPortImpl implements CBSQueryCustomerInfoTask {

    private static final Logger LOG = Logger.getLogger(CBSQueryCustomerInfoTaskPortImpl.class.getName());

    /* (non-Javadoc)
     * @see hn.com.tigo.josm.orchestrator.adapter.cbs2.task.CBSQueryCustomerInfoTask#executeTask(hn.com.tigo.josm.adapter.requesttype.v1.TaskRequestType arg0)*
     */
    public hn.com.tigo.josm.adapter.requesttype.v1.TaskResponseType executeTask(hn.com.tigo.josm.adapter.requesttype.v1.TaskRequestType arg0) throws AdapterException_Exception   {
        LOG.info("Executing operation executeTask");
        System.out.println(arg0);
        try {
            hn.com.tigo.josm.adapter.requesttype.v1.TaskResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AdapterException_Exception("AdapterException...");
    }

}
